project_name: fj
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
